# Generated by Django 3.0.6 on 2020-05-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_cat', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('source', models.TextField()),
                ('discription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('was_clicked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('session', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
